In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("https://gist.githubusercontent.com/keeganhines/59974f1ebef97bbaa44fb19143f90bad/raw/d9bcf657f97201394a59fffd801c44347eb7e28d/Hitters.csv")

In [3]:
df.head()

Unnamed: 0  AtBat  Hits  HmRun  Runs  RBI  Walks  Years  CAtBat  \
0     -Andy Allanson    293    66      1    30   29     14      1     293   
1        -Alan Ashby    315    81      7    24   38     39     14    3449   
2       -Alvin Davis    479   130     18    66   72     76      3    1624   
3      -Andre Dawson    496   141     20    65   78     37     11    5628   
4  -Andres Galarraga    321    87     10    39   42     30      2     396   

   CHits  ...  CRuns  CRBI  CWalks  League Division PutOuts  Assists  Errors  \
0     66  ...     30    29      14       A        E     446       33      20   
1    835  ...    321   414     375       N        W     632       43      10   
2    457  ...    224   266     263       A        W     880       82      14   
3   1575  ...    828   838     354       N        E     200       11       3   
4    101  ...     48    46      33       N        E     805       40       4   

   Salary  NewLeague  
0     NaN          A  
1   475.0          N  
2   480.0          A  
3   500.0          N  
4    91.5          N  

[5 rows x 21 columns]

In [4]:
df.shape

(322, 21)

In [5]:
df.isnull().sum()

Unnamed: 0     0
AtBat          0
Hits           0
HmRun          0
Runs           0
RBI            0
Walks          0
Years          0
CAtBat         0
CHits          0
CHmRun         0
CRuns          0
CRBI           0
CWalks         0
League         0
Division       0
PutOuts        0
Assists        0
Errors         0
Salary        59
NewLeague      0
dtype: int64

In [6]:
import numpy as np

In [7]:
np.mean(df['Salary']) 

535.9258821292775

In [9]:
df['Salary'].fillna(535.9258821292775,inplace = True)

In [10]:
df.head()

Unnamed: 0  AtBat  Hits  HmRun  Runs  RBI  Walks  Years  CAtBat  \
0     -Andy Allanson    293    66      1    30   29     14      1     293   
1        -Alan Ashby    315    81      7    24   38     39     14    3449   
2       -Alvin Davis    479   130     18    66   72     76      3    1624   
3      -Andre Dawson    496   141     20    65   78     37     11    5628   
4  -Andres Galarraga    321    87     10    39   42     30      2     396   

   CHits  ...  CRuns  CRBI  CWalks  League Division PutOuts  Assists  Errors  \
0     66  ...     30    29      14       A        E     446       33      20   
1    835  ...    321   414     375       N        W     632       43      10   
2    457  ...    224   266     263       A        W     880       82      14   
3   1575  ...    828   838     354       N        E     200       11       3   
4    101  ...     48    46      33       N        E     805       40       4   

       Salary  NewLeague  
0  535.925882          A  
1  475.000000          N  
2  480.000000          A  
3  500.000000          N  
4   91.500000          N  

[5 rows x 21 columns]

In [11]:
df.isnull().sum()

Unnamed: 0    0
AtBat         0
Hits          0
HmRun         0
Runs          0
RBI           0
Walks         0
Years         0
CAtBat        0
CHits         0
CHmRun        0
CRuns         0
CRBI          0
CWalks        0
League        0
Division      0
PutOuts       0
Assists       0
Errors        0
Salary        0
NewLeague     0
dtype: int64

In [12]:
dms = pd.get_dummies(df[['League', 'Division', 'NewLeague']])

df = df.drop(['Unnamed: 0'],axis = 1)

In [15]:
y = df["Salary"]

X_ = df.drop(['Salary', 'League', 'Division', 'NewLeague'], axis=1).astype('float64')

X = pd.concat([X_, dms[['League_N', 'Division_W', 'NewLeague_N']]], axis=1)

X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y, 
                                                    test_size=0.25, 
                                                    random_state=42)

<IPython.core.display.Javascript object>

In [16]:
from sklearn.linear_model import Ridge, Lasso, ElasticNet
from sklearn.metrics import mean_squared_error,r2_score

In [17]:
enet_model = ElasticNet().fit(X_train, y_train)

C:\Users\user\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:531: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 10504669.348102763, tolerance: 3821.044204947857
  positive)


In [18]:
enet_model.coef_

array([ -1.97638718,   5.27863155,   2.81696841,   0.14116193,
        -0.3552138 ,   4.65422056,  -5.98795675,  -0.24516481,
         0.63979502,   0.090477  ,   0.95231248,   0.76688832,
        -0.81120959,   0.20177722,   0.3958354 ,  -3.69834488,
         5.75091582, -36.15397187,   1.78789997])

In [21]:
enet_model.intercept_

344.4558656557311

In [22]:
enet_model.predict(X_train)[:10]

array([ 174.49774556,  562.44201308,  468.7978779 ,  449.09733796,
        324.18068689, 1006.053438  , 1714.6202318 ,  299.08590853,
        360.71862908,  589.03018609])

In [23]:
enet_model.predict(X_test)[:10]

array([ 394.52214613,  904.07330355,  297.74109126,  619.00663978,
       1103.93708093,  366.27747936,  437.53531245,  651.4546132 ,
        228.28551069,  410.68536289])

In [24]:
y_pred = enet_model.predict(X_test)

np.sqrt(mean_squared_error(y_test,y_pred))

344.3225889375409

In [25]:
r2_score(y_test,y_pred)

# """In other words, we can say that independent variables in ElasticNet Regression Model 
# explain 0.3585 % of the change in dependent variables for this data set.
# """

0.3585238942157494

In [27]:
#model tunning
from sklearn.linear_model import RidgeCV, LassoCV,ElasticNetCV
enet_cv_model = ElasticNetCV(cv = 10).fit(X_train,y_train)

# If we don't give the lambdas, what's the alpha?

enet_cv_model.alpha_

1645.5302098413063

In [28]:
enet_cv_model.intercept_

227.52899366399174

In [29]:
enet_cv_model.coef_

array([ 0.15962131,  0.14801805,  0.        ,  0.        ,  0.        ,
        0.        , -0.        , -0.31448844,  0.92428745,  0.        ,
        0.38576753,  0.6529089 , -0.06255654,  0.18808645,  0.07670846,
       -0.        ,  0.        , -0.        ,  0.        ])

In [30]:
enet_tuned = ElasticNet(alpha = enet_cv_model.alpha_).fit(X_train,y_train)

# Let's now calculate the error for the test set using this final model.

y_pred = enet_tuned.predict(X_test)

np.sqrt(mean_squared_error(y_test,y_pred))

356.77313108084206