In [98]:
from sklearn.datasets import load_diabetes

In [99]:
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split

In [100]:
X , y = load_diabetes(return_X_y=True)

In [101]:
x_train ,x_test,y_train,y_test = train_test_split(X , y ,
                                                  test_size =0.3
                                                 ,random_state=2)

In [102]:
reg = LinearRegression()
reg.fit(x_train,y_train)

LinearRegression()

In [103]:
y_pred = reg.predict(x_test)

In [105]:
r2_score(y_test,y_pred)

0.5012620528324085

In [106]:
reg.coef_

array([ -31.80536962, -214.67167622,  445.13750645,  376.35494358,
       -802.45172889,  525.95185517,  106.39967097,  172.31122486,
        799.47904182,   57.16768747])

In [107]:
reg.intercept_

152.62754194200335

In [108]:
import random
class MBGDRegressor:
    def __init__(self,batch_size,learning_rate=0.01,epochs=100):
        self.coef_ = None
        self.intercept_ = None
        self.LR = learning_rate
        self.epochs = epochs
        self.batch_size = batch_size
        
    def fit(self,x_train,y_train):
        self.intercept_ = 0
        self.coef_ = np.ones(x_train.shape[1])
        
        for i in range(self.epochs):
        
            for j in range(int(x_train.shape[0]/self.batch_size)):
                idx = random.sample(range(x_train.shape[0]),self.batch_size)

                y_hat = np.dot(x_train[idx] , self.coef_) + self.intercept_

                intercept_der = -2 * np.mean(y_train[idx] - y_hat)
                self.intercept_ = self.intercept_ - (self.LR * intercept_der)

                coef_der = -2 * np.dot((y_train[idx] - y_hat),x_train[idx])
                self.coef_ = self.coef_ - (self.LR * coef_der)

        print(self.intercept_,self.coef_)
        
    def predict(self,x_test):
        return np.dot(x_test,self.coef_) +self.intercept_

In [109]:
mbr = MBGDRegressor(learning_rate=0.01,
                    batch_size=int(x_train.shape[0]/10),
                    epochs=160)

In [110]:
mbr.fit(x_train,y_train)

151.60388312575856 [   6.86894207 -174.99861866  407.89325305  348.55607674  -20.86078269
  -83.18618733 -213.60500017  138.1190165   426.20995855  103.62836433]


In [111]:
y_pred = mbr.predict(x_test)

In [112]:
r2_score(y_test,y_pred)

0.4912752730813028

In [113]:
from sklearn.linear_model import SGDRegressor

In [115]:
sgd = SGDRegressor(learning_rate='constant',eta0=0.2)

In [142]:
batch_size = 100
for i in range(100):
    idx = random.sample(range(x_train.shape[0]),batch_size)
    sgd.partial_fit(x_train[idx],y_train[idx])

In [143]:
sgd.coef_

array([ -41.88467589, -193.75230255,  448.9554431 ,  328.88254602,
       -112.34570987,  -28.15158802, -189.74942359,  119.71913482,
        510.72693675,   66.63864232])

In [144]:
sgd.intercept_

array([153.98437641])